/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lsys.ui;

/**
 *
 * @author svejaka
 */
public class scMain extends javax.swing.JFrame {

    /**
     * Creates new form scMain
     */
    public scMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMain = new javax.swing.JPanel();
        bscHome = new javax.swing.JButton();
        bscStore = new javax.swing.JButton();
        bscProduction = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bscCustomers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bscHome.setText("Dashboard");

        bscStore.setText("Store");

        bscProduction.setText("Production");

        jButton5.setText("Tools");

        bscCustomers.setText("Customers");

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bscHome)
                .addGap(18, 18, 18)
                .addComponent(bscStore)
                .addGap(18, 18, 18)
                .addComponent(bscProduction)
                .addGap(18, 18, 18)
                .addComponent(bscCustomers)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bscCustomers, bscHome, bscProduction, bscStore, jButton5});

        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bscStore, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bscProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(bscHome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bscCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bscCustomers, bscHome, bscProduction, bscStore, jButton5});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bscCustomers;
    private javax.swing.JButton bscHome;
    private javax.swing.JButton bscProduction;
    private javax.swing.JButton bscStore;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel pMain;
    // End of variables declaration//GEN-END:variables
}
